# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install bazel
      run: |
        wget -O install.sh "https://github.com/bazelbuild/bazel/releases/download/0.26.1/bazel-0.26.1-installer-linux-x86_64.sh"
        chmod +x install.sh
        ./install.sh --user
        rm -f install.sh
    - name: Install system dependencies
      run: |
        sudo apt-get -y install libopenexr-dev
        sudo apt-get -y install libgles2-mesa-dev
        sudo apt-get -y install libc-ares-dev
        sudo apt-get -y install libc-ares-dev
    - name: Install system tools
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install flake8
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest tensorflow_graphics/nn/layer/tests/pointnet_tests.py
